- name: Linux nodes
  debug:
    msg: "FOR LINUX ONLY"

- name: Inspect nodes
  debug:
    msg: "{{ 'name: ' + item.0.name + ', path: ' + item.0.path }}"
    # msg: "{{ item.0  + ' ' + item.1 }}"
  loop: "{{ nodes_all | zip(inspected_nodes)|list }}"
  when: item.0.name == item.1